---
title: "Final Project"
output: github_document
---

```{r}
library(tidyverse)
library(maps)
```

# Clean the orginal weight dataset
```{r}
original = tibble(
  read.csv("./dataset/Student_Weight_Status_Category_Reporting_Results__Beginning_2010.csv")
) %>%
  janitor::clean_names() %>%
  select(-location_code, -region, -area_name)  # the only location information we need is county name
```

# Clean dataset with geolocation information
```{r} 
#import coordinates data set 
coordinates = tibble(
  read.csv("./dataset/Geocodes_USA_with_Counties.csv")
) %>%
  filter(state == "NY") %>%  # filter out counties outside NY state
  select(county, latitude, longitude) %>% # only information we need is county name and geolocation
  drop_na() %>%
  group_by(county) %>%
  summarise(latitude = mean(latitude), longitude = mean(longitude)) %>% #different location in each county variaed slightly, so we take the mean of each county's geolocation
  filter(!county == "") %>% # one county's name input is blank
  mutate(county = toupper(county)) # to swith county name to uppercase
```

# combine two data set
```{r}
weight_df = left_join(original, coordinates, by = "county")

average_percent = 
  weight_df %>% 
  group_by(county) %>% 
  drop_na(percent_overweight_or_obese) %>%
  summarize(average = mean(percent_overweight_or_obese), .groups = "keep")

sum_df = left_join(weight_df, average_percent, by = "county")
```

```{r}
counties <- map_data("county")
ny_county <- subset(counties, region == "new york") %>% 
  rename(county = "region")

leafmap = merge(ny_county, sum_df, by = "county" )
```





