---
title: "Mapping and Visualization"
output: html_document
---

```{r setup, include = FALSE}
library(tidyverse)
library(plotly)
library(rgdal)
library(plotly)
library(maps)
library(devtools)
library(leaflet)
library(BAMMtools)
library(spdep)
library(maptools)

knitr::opts_chunk$set(
  message = FALSE,
  warning = FALSE,
  fig.width = 10,
  fig.asp = .6,
  out.width = "90%"
)

theme_set(theme_minimal() + theme(legend.position = "bottom"))

options(
  ggplot2.continuous.colour = "viridis",
  ggplot2.continuous.fill = "viridis"
)

scale_colour_discrete = scale_colour_viridis_d
scale_fill_discrete = scale_fill_viridis_d

```

```{r, include = FALSE}
# Clean the orginal weight dataset
original = tibble(
  read.csv("./dataset/Student_Weight_Status_Category_Reporting_Results__Beginning_2010.csv")
) %>%
  janitor::clean_names() %>%
  select(-location_code, -region, -area_name)  # the only location information we need is county name
```

```{r, echo = FALSE} 
# Clean dataset with geolocation information
fips_code = tibble(
  read.csv("./dataset/New_York_State_ZIP_Codes-County_FIPS_Cross-Reference.csv")
) %>%
  janitor::clean_names() %>% 
  rename("county" = county_name, "fips" = county_fips) %>% 
  select(county, fips) %>% # only information we need is county name and geolocation
  distinct() %>% 
  mutate(county = toupper(county)) # to swith county name to uppercase
```

```{r, echo = FALSE}
weight_df = 
  left_join(original, fips_code, by = "county") %>% 
  filter(county != "STATEWIDE (EXCLUDING NYC)")
  
average_percent = 
  weight_df %>% 
  group_by(county) %>% 
  drop_na(percent_overweight_or_obese) %>%
  summarize(average = mean(percent_overweight_or_obese), .groups = "keep")

sum_df = 
  left_join(average_percent, fips_code, by = "county") %>% 
  mutate(fips_code = as.character(fips))
```


```{r, include = FALSE}
#zip code tabulation area
fips_map = readOGR(dsn = "./dataset/NYS_Civil_Boundaries_SHP/Counties.shp", encoding = "UTF-8")

fips_map@data<- left_join(fips_map@data, sum_df, by = c("FIPS_CODE" = "fips_code"))

fips_map$average[is.na(fips_map$average)] <- 0
```

```{r, echo = FALSE}
# CRS setting
fips_map_crs = spTransform(fips_map, CRS("+init=epsg:4326"))
# export the json file
writeOGR(fips_map_crs, './dataset/fips_map_geojson', layer = 'fips_map', driver = 'GeoJSON')
```

```{r, include = FALSE}
# Layout 
# format of the label that pops up for each polygon
label_popup = paste0(
  "<strong>FIPS code: </strong>",
  fips_map$FIPS_CODE,
  "<br><strong>County Name: </strong>",
  fips_map$NAME,
  "<br><strong>Percent of overweight or obses children: </strong>",
  fips_map$average
)

# get jenks natural break for average
getJenksBreaks(fips_map$average, 5)

# set bins
average_bins <- c(26,30,34,38,43)

# set pals
average_pal <- colorBin('Blues', bins = average_bins, na.color = '#9fabab')
```

### The Spacial Trend of the Average Percentage of Overweight or Obese Student population by Counties in New York State:

```{r, echo = FALSE}
# choropleth map
leaflet::leaflet(data = fips_map_crs) %>% 
  addProviderTiles('CartoDB.Positron') %>% 
  addPolygons(fillColor = ~average_pal(average),
              fillOpacity = 0.8,
              color = "#BDBDC3",
              weight = 1,
              popup = label_popup,
              highlightOptions = highlightOptions(color = "black", weight = 2,
      bringToFront = TRUE)) %>% 
  addLegend('bottomleft',
            pal = average_pal,
            values = ~average,
            title = "The Average Percentage of Overweight or Obisity in New York",
            opacity = 1)
```
_The darker the blue color, the larger percentage of overweight or obesity can be found in the corresponding county_